security:
  oauth2:
    client:
      client-id: xiao1
      client-secret: jianjun1
      user-authorization-uri: http://127.0.0.1:8090/server/oauth/authorize
      access-token-uri: http://127.0.0.1:8090/server/oauth/token
    resource:
      jwt:
        key-uri: http://127.0.0.1:8090/server/oauth/token_key
server:
  port: 8091
  context-path: /client1